# Packages up the dotnet new commands so you can install them. 
# 
name: Package

env:
  OUTPUT: ./Output
  PACKAGE_NAME: Umbraco.Packages.Templates

# happens when a commit is tagged release/[version]
on:
  push:
    tags:
      - "release/*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-package:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Version 
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/release\//}
        shell: bash

      - name: checkout
        uses: actions/checkout@v2
        
      - name: Setup .net core
        uses: actions/setup-dotnet@v1.4.0
        
      - name: package
        run: dotnet pack -o ${{ env.OUTPUT }} /p:version=${{ steps.get_version.outputs.VERSION }}
     
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v${{ steps.get_version.outputs.VERSION }}
          body: | 
            New Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: true
          
      - name: Upload Release Asset      
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.OUTPUT }}/${{ env.PACKAGE_NAME }}.${{ steps.get_version.outputs.VERSION }}.nupkg
          asset_name: ${{ env.PACKAGE_NAME }}.${{ steps.get_version.outputs.VERSION }}.nupkg
          asset_content_type: application/zip
      
       
       

